### ISSUE TITLE
Kitchen Display View does not show any order after latest update

### ISSUE THREAD

**Issue by bingo-bonzai** [ryanmitchell/ti-ext-kitchendisplay#26]
**Expected behavior:**
Kitchen Display View should show a list of orders as per the selected status filter.

**Actual behavior:**
Kitchen Display View show's blank in spite of setting a valid order status filter. I have tried for all Statuses and as well as each specific status. It still does not list any orders.

**Reproduction steps:**
1. Create a new Kitchen Display view
2. Under view creation form set the "Orders with initial status" field to "Pending Preparations" or any other status.

**Version:**
v3.0.4.-beta 24.4

**View Settings**
![image](https://user-images.githubusercontent.com/71254245/100342017-6015ab00-3003-11eb-9dd9-c5a7d28bb182.png)

**Blank Kitchen Display view**
![image](https://user-images.githubusercontent.com/71254245/100342061-6b68d680-3003-11eb-88fa-6ce856335c74.png)

**Comment by ryanmitchell** [comment]
This this was fixed here: https://github.com/ryanmitchell/ti-ext-kitchendisplay/commit/def37888e1cdf888b8c634128b39e3614f4402b7

**Comment by roydeanjr** [comment]
Don't forget to tag so it rolls into Marketplace. Current version there is still 2.0.1.

**Comment by ryanmitchell** [comment]
Done 👍

**Comment by bingo-bonzai** [comment]
Today updated KD to v 2.0.1 however order listing issue still persists. 
While the Marketplace shows v 2.0.2 this version is still not visible under TI->Admins->System->Updates. Is there a lag between tagging and visibility of an update in the TI's Updates section?

**Comment by roydeanjr** [comment]
There is a lag. Does take some time, that said, my anomaly is different: update showed as needed, but it still said 2.0.1. I did not update. Left the system for quite a while, came back and the KD does display orders yet the Marketplace says 2.0.2 AND the installed extension says 2.0.1 AND the view shows orders. Not sure what is the truth!

**Comment by bingo-bonzai** [comment]
Pls refer to my View settings snapshot in the issue description above. Do you see any discrepancies in the selected settings that may be causing this issue?

**Comment by ryanmitchell** [comment]
The 2.0.2 update should fix it. You can see the code changed in the commit and apply it yourself to see if it helps. 

If not debug the issue and open a PR

**Comment by roydeanjr** [comment]
Same update issue as updating to v2! Removing extension and attempted reinstall does not install 2.0.2. Did v2.0.2 actually get released?

**Comment by ryanmitchell** [comment]
Yes.

**Comment by roydeanjr** [comment]
I'm still looking into the update issue. I'll keep you posted.

**Comment by roydeanjr** [comment]
The update / install process is not working. I am going to have to manually add the extension back to my site.

**Comment by roydeanjr** [comment]
Strangest thing! Manually uploaded the latest download and the version reads v1.0.0! I look at the extension.json and it reads 2.0.2! Why would that be occuring? I cleared cache before uploading the latest release.

**Comment by ryanmitchell** [comment]
No idea how the updates work sorry.

**Comment by bingo-bonzai** [comment]
> site

Same here....i tried checking update today again however 2.0.2 still didn't show up so tried to uninstall and install it. but its not installing 2.0.2, strange...

Sam may be able to throw some light on the Install logic, but i cant see him on this Repo.

@ryanmitchell will it make sense to merge this extension into the TI branch so that code maintenance and issue management would be easier. What do you say?

**Comment by ryanmitchell** [comment]
No, this is a standalone extension - we are trying to reduce core rather than add to it.
Sam has nothing to do with Kitchen Display which is why he isnt here 😄 
I'll release a v2.0.3 now to try and get it to update for you.

**Comment by roydeanjr** [comment]
Interesting...... Here is something I noticed and a bit of my own experience.
1 - the releases are not in order....if you look at the release page, 2.0.2 is listed after 2.0.1. It seems that the release listed at the top is the one that is picked up by TI. But what do I know for sure?

2 - my experience with KD updating, on another install on my own development environment (which I have set up and TI does work), I removed the extension manually and copied from all different releases. None of the releases show correctly. In fact, when I look at the release in the json file and what appears on the extension page, they are not ever matching. 

3 - in my development install, KD does not display any orders. Oddly, even while my site on a shared host does show orders. This case is odd because I copied the code from the shared host site that does show orders and placed in into the development site, still no orders.

I will see what happens when I update to the latest version. Thank you, Ryan for pursuing this with us!

**Comment by roydeanjr** [comment]
Update reflects correctly in the Extensions list on the shared host site! Yay! And, orders still show in the KD View I created......

Update refects correctly in my development site! Yay! Orders do not show!

This is really weird. I did the same thing on my development site as I have always done on my shared host site: change the status of some existing orders to Received rather than enter new orders. I am about to enter some new orders on my dev site. I will report once that is completed.

**Comment by roydeanjr** [comment]
Hmm.... New order on dev site does not show in the KD View.......I even created a new view and still no orders.
![image](https://user-images.githubusercontent.com/36243458/100462716-49696580-3090-11eb-98ce-8ac43c1bb50d.png)
![image](https://user-images.githubusercontent.com/36243458/100462747-55edbe00-3090-11eb-8953-c677c5a8a94b.png)
![image](https://user-images.githubusercontent.com/36243458/100462786-61d98000-3090-11eb-95ec-67a2330aea8a.png)

**Comment by ryanmitchell** [comment]
You’d need to debug the query and work out the cause.

It’s working ok for me in my environment. 

I’m sure there is an issue but you need to work out where it’s coming up.

**Comment by roydeanjr** [comment]
I understand. That is the part of the development environment I have not perfected yet.

**Comment by ryanmitchell** [comment]
Anything in the error log?

**Comment by roydeanjr** [comment]
No errors in the error log related to the query or anything with the KD.

**Comment by roydeanjr** [comment]
Ryan, I have been walking through the debug process and for whatever reason, the index.php page under customerdisplay/views/summary is getting executed and I keep having to click Resume or press F9 to get the webpage to finish and render.

I removed the customerdisplay extension and that made the debugger open index.php from the root folder, interesting though, it seems the KD summary is not getting executed as the breakpoint I set on $getorders never does get executed.

Or, maybe my environment is not setup like it needs to be to facilitate debugging like I want.

**Comment by ryanmitchell** [comment]
Maybe remove the index.php - it should be index.blade.php now so the .php ones can be removed.

**Comment by roydeanjr** [comment]
In customerdisplay? Have you modified that?

**Comment by ryanmitchell** [comment]
Oh sorry misread. Yeah I probably need to update customer display for blade.

**Comment by ryanmitchell** [comment]
Just so I’m clear. If you turn off customer display then kitchen display works fine?

**Comment by roydeanjr** [comment]
No, it still is not working. I opened controllers/summary.php and set a breakpoint on $getorders line. Then opened my browser to navigate to the View button, clicked it and still get a blank page. The debugger did not stop at the breakpoint. Nor did it open summary.php to even reflect that it was getting executed on the server.

**Comment by roydeanjr** [comment]
I may not have the debugger set right, as the absolute path on the server is not being detected. I changed that and now I get the breakpoint encountered. I'll review this and get back to you.

**Comment by roydeanjr** [comment]
Seems like stepping through the code, it never steps into `foreach ($getOrders as $orderIdx => $order)`. I set a breakpoint at `$runningdishes = [];` and the debugger never stopped at that line. I suppose suggesting that no orders were returned. 

I am having a hard time finding the query that is being executed.

**Comment by ryanmitchell** [comment]
Its the $getOrders = … line block

Comment out the if (x) $query-> lines until you get orders and that’ll help diagnose where the point of the issue is.

**Comment by roydeanjr** [comment]
Ah, ok, will do.

**Comment by roydeanjr** [comment]
Commented all if (x) and still no orders. Tried changing roles, permissions, etc. and still no orders. Is it possibly a memory issue? Wouldn't an error be seen if the server is out of memory?

**Comment by ryanmitchell** [comment]
Doubt it will be memory.

Have you tried turning on error displays:

ini_set(‘display_errors’, ‘on’)

**Comment by roydeanjr** [comment]
Have not. Interesting situation, using VSCode and running with debug, I get an exception about invalid payload, however, when I run without debugging I get a blank page.

Invalid payload is stopping the code at line 195 in vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php. Is that an anomaly while debugging? 
![image](https://user-images.githubusercontent.com/36243458/100519970-de3b9400-3160-11eb-9a73-ca1f2836c7f2.png)


If I encounter that error and then stop debugging I get this in the browser:
(1/1) FatalErrorExceptionUncaught Illuminate\Contracts\Encryption\DecryptException: The payload is invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:195Stack trace:#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(136): Illuminate\Encryption\Encrypter->getJsonPayload(NULL)#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(110): Illuminate\Encryption\Encrypter->decrypt('en', false)#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(84): Illuminate\Cookie\Middleware\EncryptCookies->decryptCookie('pma_lang', 'en')#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Cookie\Middleware\EncryptCookies->decrypt(Object(Illuminate\Http\Request))#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)
--
in Encrypter.php line 195
at FatalErrorException->__construct('message' => '???', 'code' => '???', 'severity' => '???', 'filename' => '???', 'lineno' => '???', 'traceOffset' => '???', 'traceArgs' => '???', 'trace' => '???', 'previous' => '???')in HandleExceptions.php line 148
at HandleExceptions->fatalExceptionFromError('error' => '???', 'traceOffset' => '???')in HandleExceptions.php line 134
at HandleExceptions->handleShutdown()in HandleExceptions.php
at Encrypter->getJsonPayload('payload' => '???')in Encrypter.php line 136
at Encrypter->decrypt('payload' => '???', 'unserialize' => '???')in EncryptCookies.php line 110
at EncryptCookies->decryptCookie('name' => '???', 'cookie' => '???')in EncryptCookies.php line 84
at EncryptCookies->decrypt('request' => '???')in EncryptCookies.php line 67
at EncryptCookies->handle('request' => '???', 'next' => '???')in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure:/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:147-180}('passable' => '???')in Pipeline.php line 105
at Pipeline->then('destination' => '???')in Router.php line 683
at CoreRouter->runRouteWithinStack('route' => '???', 'request' => '???')in Router.php line 658
at CoreRouter->runRoute('request' => '???', 'route' => '???')in Router.php line 624
at CoreRouter->dispatchToRoute('request' => '???')in CoreRouter.php line 20
at CoreRouter->dispatch('request' => '???')in Kernel.php line 170
at Kernel->Illuminate\Foundation\Http\{closure:/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:167-171}('request' => '???')in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure:/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128-136}('passable' => '???')in SaveSetting.php line 27
at SaveSetting->handle('request' => '???', 'next' => '???')in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure:/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:147-180}('passable' => '???')in TrustProxies.php line 57
at TrustProxies->handle('request' => '???', 'next' => '???')in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure:/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:147-180}('passable' => '???')in TransformsRequest.php line 21
at ConvertEmptyStringsToNull->handle('request' => '???', 'next' => '???')in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure:/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:147-180}('passable' => '???')in ValidatePostSize.php line 27
at ValidatePostSize->handle('request' => '???', 'next' => '???')in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure:/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:147-180}('passable' => '???')in CheckForMaintenanceMode.php line 63
at CheckForMaintenanceMode->handle('request' => '???', 'next' => '???')in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure:/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:147-180}('passable' => '???')in Pipeline.php line 105
at Pipeline->then('destination' => '???')in Kernel.php line 145
at Kernel->sendRequestThroughRouter('request' => '???')in Kernel.php line 110
at Kernel->handle('request' => '???')in index.php line 53
at {main}()in index.php

**Comment by ryanmitchell** [comment]
Don’t think this is anything to do with KD and I don’t use VScode sorry.

**Comment by roydeanjr** [comment]
Not sure whether it is a debugging issue or what, but I get similar behavior when I use PHPStorm to debug. I just don't see the issue as PHPStorm doesn't stop and show the code but it does stop. I have to hit F9 a few times to get the blank page. Seems odd that I have to hit F9 to keep the page loading. Why wouldn't it just load and stop at a breakpoint?

**Comment by ryanmitchell** [comment]
I don’t use php storm either. 
Sorry - without an error message I can’t help!

**Comment by roydeanjr** [comment]
I stepped through some more and the line 140 and 144 `unset($menuItems[$menuIdx]);` and I can watch as the array goes from some number down to 0. Then the line 149 checks the $menuItems array and if 0 just continues. It appears it is always counting down to 0 and thus continueing since there are no items.

**Comment by roydeanjr** [comment]
I just commented out lines 149-152 and I get cards but no menu items displayed.

**Comment by roydeanjr** [comment]
I can click a button and get it to change the status as well. So that part is working.

**Comment by roydeanjr** [comment]
I am in controllers/summary.php.

**Comment by roydeanjr** [comment]
Commenting out lines 134-145 I get details on the display.

**Comment by ryanmitchell** [comment]
Line 141-4 is being called where you have set categories on the view settings, but the menu item has no categories so it removes the item from the view as there is no category match

**Comment by roydeanjr** [comment]
I have all the categories selected.

**Comment by roydeanjr** [comment]
What does this line actually compare: `$menu->category_priority = $menuModel->categories[0]->priority;`?
I don't have my categories set to priority = 100.

**Comment by ryanmitchell** [comment]
I’ll look later. It’s late on a Saturday night for me and I don’t really want to work :)

**Comment by roydeanjr** [comment]
I understand. I am surprised you are still up until I remember it is Saturday night! LOL! Thanks for the input. Have a great rest of night and Sunday!

**Comment by ryanmitchell** [comment]
See if this helps: https://github.com/ryanmitchell/ti-ext-kitchendisplay/commit/d149a602d754202602df3367e6416e0b61beb2c8

**Comment by roydeanjr** [comment]
That did not help. Another thing I noticed, with all statuses selected, I only get one order; the one that is in prep. All other orders do not show. Additionally, when I tested each status, the orders show for each status, but the orders selected does not totally match the orders in the list.
The following is the result of each status selection I made. I have 2 orders that are Received and one that is in Prep:
All status -> 1 order (the one in prep)
Received -> 3 orders
Pending -> 1 order (the one in prep)
Preparation -> 1 order (the one in prep)
Delivery -> 1 order (the one in prep)
Cancelled -> 1 order (the one in prep)
Ready -> 1 order (the one in prep)
Completed -> maximum number of orders

I know this is occurring because I have commented out lines 135-145, but something besides what I commented out is not working correctly.

**Comment by ryanmitchell** [comment]
Is this still on your dev server? Does it work properly on your live environment?

**Comment by roydeanjr** [comment]
Live environment is working without any changes. I even copied the code form live to dev and still did not work on dev. Weird. I will check out the results of different status on live (shared host) site and post results here.

**Comment by roydeanjr** [comment]
From my shared host site, the following is the result of each status selection I made. I have 3 orders that are not complete and 2 in Prep, 1 Ready:
All status -> 3 orders
Received -> 3 orders
Pending -> 3 orders
Preparation -> 3 orders
Delivery -> 3 orders
Cancelled -> 3 orders
Ready -> 3 orders
Completed -> maximum number of orders

**Comment by ryanmitchell** [comment]
Sorry this means nothing to me as I have no context on hte orders.
Are you saying its working or not?

**Comment by roydeanjr** [comment]
The first statement gives context of the orders I have in my system. The rest is the results of what happens when I select just that status for the View. It is not working. Cancelled should not show any orders, there are no orders with the status cancelled in my system, etc.

**Comment by roydeanjr** [comment]
My opinion is that the results are getting messed up with the implementation of the category selection restrictions. Before that, the status selection was working fine and I could have multiple views showing the exact orders I want at each "station". My stations were Kitchen, Delivery and Pickup. I was able to restrict orders in the Kitchen if they were Received and no order showed in Delivery or Pickup until the order was changed to Ready in the Kitchen.

**Comment by ryanmitchell** [comment]
I think there may be 2 issues, this fix should handle the status issue:
https://github.com/ryanmitchell/ti-ext-kitchendisplay/commit/f0aea1221a92468d9944fc428574488f8952c854

Once we get the statuses appearing correctly we can look at the categories issue if it still exists. Lets stay focused on one at a time 😄

**Comment by roydeanjr** [comment]
Yes, there are multiple issues with the "what displays" options.

That change did not fix the status selection restrictions. I still get orders where there are none in the system with a selected status.

**Comment by ryanmitchell** [comment]
Have you applied the entire file, including reinstating bits you have commented out? Its definitely limiting the statuses correctly for me.

**Comment by roydeanjr** [comment]
Yes, I did not comment out on the shared host site. Unless you changed something else out, the shared site is the one I tested with.

The dev site I failed to uncomment. I will try that.

**Comment by ryanmitchell** [comment]
You'd need to dump $statuses around line 98 to see whats going on then - its definitely working as expected for me.
Bear in mind it pulls in the status of your button 1 action and button 2 action too so they continue to be shown.

**Comment by roydeanjr** [comment]
So, when I uncomment I get nothing on my dev site.

**Comment by ryanmitchell** [comment]
Thats probably to do with category selection - comment out lines 136 - 151 for now.
If the order count is correct then we can uncomment those and work out what categories should be appearing and why they arent.

**Comment by roydeanjr** [comment]
So, the button statuses as well as the initial status? That would explain why I get 3 orders when all the statuses were tested individually, I did not change the button statuses. I will test again on both sites and create a view with the corresponding button statuses. That may need to be clearly noted so others don't get confused about why orders are showing up when they should not be. Good note!

**Comment by ryanmitchell** [comment]
Yes. Otherwise it would drop from the list when you set the status.

**Comment by roydeanjr** [comment]
Ok, looks like with everything set, I get the correct orders displaying. However, the code is different local dev site vs shared hosting site.

Local dev site I commented out lines 142-150.

**Comment by ryanmitchell** [comment]
Ok that’s to do with categories so we are getting somewhere. 

What are you category settings and do your menu items all have categories assigned to them?

**Comment by roydeanjr** [comment]
Yes, all menu items are in categories. My categories for the views are All selected. As far as their values, Main=12, Sides=11, Specials=14, Catering=15 and In a Pile=16.

**Comment by ryanmitchell** [comment]
I've stepped down through the code this morning and its all correct. Make sure you are using the full Controller/Summary.php from the last commit so we are sure we're working off the same code base.

You'd need to debug it on your side to see whats going on - it could be something in your dev set up. 

If you are seeing code get to line 150 then that means there are items with no categories assigned, which shouldn't be the case from what you are saying.

Line 144 checks for category matching between menu item category and the ones selected in the view - again I've tested and this is working.

**Comment by roydeanjr** [comment]
Oddly, line 137 is false so only line 150 is executed. From what I can see, menuModel->categories is not even listed in the array of menuItems.
![image](https://user-images.githubusercontent.com/36243458/100659904-e89f8e80-3316-11eb-9967-7fc2a24137ec.png)

**Comment by ryanmitchell** [comment]
Odd indeed. Are you definitely using the latest version of TI?

**Comment by roydeanjr** [comment]
TI is at 24.4 on my dev, local site. Same with my shared hosting site, however, on my dev site (local) I did update the code to the current latest updates. My shared host site contains the released code that matches 24.4.

Is that clearly understood? I suppose I could revert, however, this anomaly existed before I updated the local dev site.

**Comment by roydeanjr** [comment]
Also, from what I can see, my dev site includes mariadb v10.2.34-MariaDB-1:10.2.34+maria~bionic-log while my shared host site has v5.6.50-cll-lve - MySQL Community Server.

**Comment by ryanmitchell** [comment]
Hmm it could be a Maria vs MySQL issue. Something weird for sure - not sure I can help much sorry!

**Comment by roydeanjr** [comment]
Not sure. I tried with mssql 5.7 and that did not show any orders either. Too much time on this, have to trust that my shared host site is going to be the one I use going forward. Can only wait for new releases to see if any issues I have really have been worked out. Thank you for your help.

**Comment by bingo-bonzai** [comment]
@ryanmitchell @roydeanjr , Guys finally i was able to update KD to v2.0.3 however the view are still showing blank. No orders displayed though there are quite a no. of sample orders that meet the view filter conditions.
Any clue what's wrong? Am i missing anything?

**Comment by ryanmitchell** [comment]
Hard to know without seeing your set up. 

Try using the latest GitHub version - there’s been some changes not released yet.

**Comment by roydeanjr** [comment]
@bingo-bonzai Please take a screenshot of one of the menu item setup pages showing the category the menu item is assigned. Then show the settings for the view as well as the order the item was ordered on.

**Comment by roydeanjr** [comment]
@ryanmitchell Soooo........I owe you an apology! I had been testing with my development install and THOUGHT all the menu items had categories assigned......Seems I was mistaken! I am sorry for taking you on a goose chase!

Right now, after updating my live site, rdqbbq.com, I am able to get orders to display without issue! As long as all the menu items have categories assigned, you will get orders in the KD Views.

Thank you for your patience, All is good from my side!

**Comment by ryanmitchell** [comment]
Ha its ok - these things happen! I knew I wasnt going crazy!

**Comment by bingo-bonzai** [comment]
@roydeanjr @ryanmitchell , guys any update on this front..? My KD view still remains blank...

**Comment by ryanmitchell** [comment]
No reason for it to be happening with the latest codebase. If it still is you would need to debug the summary controller and see if you can figure out the reason why.

**Comment by bingo-bonzai** [comment]
> @ryanmitchell Soooo........I owe you an apology! I had been testing with my development install and THOUGHT all the menu items had categories assigned......Seems I was mistaken! I am sorry for taking you on a goose chase!
> 
> Right now, after updating my live site, rdqbbq.com, I am able to get orders to display without issue! As long as all the menu items have categories assigned, you will get orders in the KD Views.
> 
> Thank you for your patience, All is good from my side!
@roydeanjr @ryanmitchell Gotcha, my bad. 

Like Roy pointed out, it was the unset Menu Item Category which was the core issue. After setting Categories for all my Menu items the KD is working just fine...

Better to add this setup step as part of the Extension documentation OR the update View filter logic to include None Category as well so that even the MenuItems with unset category but part of the orders would get displayed.

What do you say?

**Comment by ryanmitchell** [comment]
If you choose a category in the view output settings then it should not show uncategorised menu items in my opinion.

**Comment by bingo-bonzai** [comment]
@ryanmitchell, agree... that's why I suggested to include "None" option under KD->View->"Show menu items from categories" so that it can be used to display even uncategorized Menu Items. Not everyone might set a category for their Menu item.

If we think its otherwise then we may either update the extension documentation indicating a mandatory setup of Categories for all Menu items as a prerequisite OR enforce a validation rule to select Category while creating a Menu Item itself. This is more from UX perspective.

**Comment by ryanmitchell** [comment]
Yep! feel free to open a PR with the none option.

**Comment by roydeanjr** [comment]
I think the None or All (include any menu item, categorized or not) would be best as we would get pushback if category is all of a sudden a required field when creating a menu item.

The reason I didnt have categories is because the upgrade process does not successfully migrate the category. Not sure why, have raised it as an issue with Sam, but to no avail. May try again.

**Comment by ryanmitchell** [comment]
This *should* be how it currently works in the latest codebase (not yet released). If there are no categories selected (which is the same as selecting all) then it should ignore the category restrictions.

Cn you download the master zip from Github and test

**Comment by roydeanjr** [comment]
Download master zip from KD or TI?

**Comment by ryanmitchell** [comment]
From this repository

**Comment by roydeanjr** [comment]
Ok, help me understand......
View orders ready to process -  [Thoughtco.KitchenDisplay.View] is the exact name of the View?
View orders ready to be collected by customers -  [Thoughtco.CustomerDisplay.View] is the exact name of the View?

I have two views set up; Received and Complete are the names, but both of those views are available to the Kitchen user even though I only checked "View orders ready to process" in the Roles page under Users.

**Comment by ryanmitchell** [comment]
No, there is no per view limitation in place. Its all or nothing.

**Comment by roydeanjr** [comment]
I see. So, what do those two settings do exactly?

**Comment by ryanmitchell** [comment]
Thoughtco.KitchenDisplay.Manage lets you manage the setup of views

Thoughtco.KitchenDisplay.View lets you view the views

**Comment by roydeanjr** [comment]
Got it. So are the two I mentioned above left over from a previous version? I should have deleted the version before copying the new bits into the folder, right?

**Comment by ryanmitchell** [comment]
No, Thoughtco.CustomerDisplay.View is for the Customer Display extension, nothing to do with this one.

Thoughtco.KitchenDisplay.View is still used.

**Comment by roydeanjr** [comment]
Ah, missed that nuance!! Thank you for your patience.

**Comment by roydeanjr** [comment]
Looks like no category does display all the orders.

**Comment by roydeanjr** [comment]
I say, roll it out! Good work @ryanmitchell !

**Comment by ryanmitchell** [comment]
Done
